W-14783819: Add query parameters example.
mulesoft/pdk-custom-policy-examples pull request #10
Opened 2024-01-17 18:31 UTC by JaatadiaMulesoft

2024-01-17 20:30 UTC, andytesti commented on query/tests/requests.rs
> +const QUERT_CONFIG_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/requests/query");
Is this `QUERT` a typo?

2024-01-19 13:22 UTC, JaatadiaMulesoft commented on query/tests/requests.rs
> +const QUERT_CONFIG_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/requests/query");
indeed

2024-01-19 13:43 UTC, balbifm requested changes

2024-01-19 13:43 UTC, balbifm commented on query/src/lib.rs
> +async fn inner_request_filter(
Can we remove the query params that are being moved to the headers as well? In that way we are showing how to read, and remove query params. We would still be missing the adding part though

2024-01-19 18:00 UTC, balbifm approved these changes

2024-01-19 18:02 UTC, merged